apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    type: database
  name: posgres-cont
spec:
  containers:
  - image: postgres
    name: pod
    resources: {}
    envFrom:
      - configMapRef:
          name: postgres-config
    ports:
      - containerPort: 5432
        protocol: TCP

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
