apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    type: database
  name: posgres-service
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      #nodePort: 30010
  selector:
    type: database
  type: NodePort
status:
  loadBalancer: {}
